services:
  mariadb:
    container_name: portfolio_mariadb
    image: mariadb:10.5
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    env_file:
      - .env
    networks:
      - portfolio
    volumes:
      - volume_mariadb:/var/lib/mysql
  
  api:
    container_name: portfolio_api
    image: harbor.m-loeffler.de/portfolio/api:latest
    networks:
      - portfolio
    depends_on:
      - mariadb
    environment:
      DB_HOST: mariadb
      DB_PORT: 3306
      DB_USER: ${MYSQL_USER}
      DB_PASS: ${MYSQL_PASSWORD}
      DB_NAME: ${MYSQL_DATABASE}
    env_file:
      - .env

  client:
    container_name: portfolio_client
    image: harbor.m-loeffler.de/portfolio/client:latest
    networks:
      - portfolio
    ports:
      - "80:80"
    depends_on:
      - api

volumes:
  volume_mariadb:
    name: portfolio_mariadb

networks:
  portfolio:
    driver: bridge